name: Build
on: [push, pull_request]

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: install dependencies
      run: npm install
    - name: build new debug
      run: npm run build
    - name: build new release
      run: npm run build-release
    - name: build old debug
      run: npm run build-old
    - name: build old release
      run: npm run build-old
    - name: package
      run: npm run make

  build_on_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: install dependencies
      run: npm install
    - name: build new debug
      run: npm run build
    - name: build new release
      run: npm run build-release
    - name: build old debug
      run: npm run build-old
    - name: build old release
      run: npm run build-old
    - name: package
      run: npm run make

  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: install dependencies
      run: npm install
    - name: build new debug
      run: npm run build
    - name: build new release
      run: npm run build-release
    - name: build old debug
      run: npm run build-old
    - name: build old release
      run: npm run build-old
    - name: package
      run: npm run make